export const GET_FEATURED_PODCASTS_LIST = 'CADENCE.GET_FEATURED_PODCASTS_LIST'
export const GET_CATEGORIES_LIST_SUCCESS = 'CADENCE.GET_CATEGORIES_LIST_SUCCESS'
export const GET_CATEGORIES_LIST_FAIL = 'CADENCE.GET_CATEGORIES_LIST_FAIL'

export const CREATE_FEATURED_PODCAST = 'CADENCE.CREATE_FEATURED_PODCAST'
export const CREATE_CATEGORY_SUCCESS = 'CADENCE.CREATE_CATEGORY_SUCCESS'

export const DELETE_FEATURED_PODCAST = 'CADENCE.DELETE_FEATURED_PODCAST'
export const DELETE_CATEGORY_SUCCESS = 'CADENCE.DELETE_CATEGORY_SUCCESS'

export const UPDATE_FEATURED_PODCAST = 'CADENCE.UPDATE_FEATURED_PODCAST'
export const UPDATE_CATEGORY_SUCCESS = 'CADENCE.UPDATE_CATEGORY_SUCCESS'

export const CONFIRM_AND_DELETE_FEATURED_PODCAST = 'CADENCE.CONFIRM_AND_DELETE_FEATURED_PODCAST'
export const UPDATE_CATEGORIES = 'CADENCE.UPDATE_CATEGORIES'
export const UPDATE_CATEGORIES_PRIORITY_SUCCESS = 'CADENCE.UPDATE_CATEGORIES_PRIORITY_SUCCESS'
