export const GET_PODCASTS_LIST = 'CADENCE.GET_PODCASTS_LIST'
export const GET_PODCAST_DETAILS = 'CADENCE.GET_PODCAST_DETAILS'
export const UPDATE_PODCAST_DETAILS = 'CADENCE.UPDATE_PODCAST_DETAILS'
